# This is a sample configuration file for the Linux watchdog(8) daemon
# The watchdog daemon will monitor the helo files written by udpbohrer and 
#tcpbohrer.
# If they cannot exchange helo messages within the specified change time,
# the system resets. This retriggers reconfiguration of network interfaces
# and may resolve transient network issues.

watchdog-device = /dev/watchdog
interval = 10


file = /tmp/udpbohrer.helo
change = 1200
file = /tmp/tcpbohrer.helo
change = 1200